; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
lib_deps = 
	bblanchon/ArduinoJson@^7.3.0
	me-no-dev/AsyncTCP@^3.3.2
	me-no-dev/ESPAsyncWebServer@^3.6.0
	iakop/LiquidCrystal_I2C_ESP32@^1.1.6
	adafruit/Adafruit SSD1306@^2.5.7
	adafruit/Adafruit GFX Library@^1.11.9
monitor_speed = 115200

; Debug levels [when pushing to production set to 0]
; 0: No debug output
; 1: Errors only (default)
; 2: Warnings + Errors
; 3: Info + Warnings + Errors
; 4: Debug + Info + Warnings + Errors
; 5: Verbose + Debug + Info + Warnings + Errors
build_flags = -DCORE_DEBUG_LEVEL=0

[platformio]
src_dir = firmware/src
lib_dir = firmware/lib
include_dir = firmware/include
test_dir = firmware/test
data_dir = firmware/data
build_dir = firmware/.pio/build
libdeps_dir = firmware/.pio/libdeps


